export const ALL_STATES = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Andaman & Nicobar Islands",
  "Chandigarh",
  "Dadra & Nagar Haveli and Daman & Diu",
  "Delhi (NCT)",
  "Jammu & Kashmir",
  "Ladakh",
  "Lakshadweep",
  "Puducherry",
] as const;

export const ALL_DEPARTMENTS = [
  "Agriculture Department",
  "Animal Husbandry & Dairying",
  "Civil Aviation",
  "Coal Ministry",
  "Commerce & Industry",
  "Consumer Affairs",
  "Cooperation",
  "Culture Department",
  "Defence Department",
  "Disaster Management",
  "Education Department",
  "Election Commission",
  "Environment & Climate",
  "Finance Department",
  "Fisheries Department",
  "Food & Public Distribution",
  "Forest Department",
  "General Administration",
  "Health & Family Welfare",
  "Higher Education",
  "Home Department",
  "Horticulture Department",
  "Housing & Urban Affairs",
  "Information & Broadcasting",
  "Irrigation Department",
  "IT & Electronics",
  "Jal Shakti / Water Resources",
  "Labour & Employment",
  "Law Department",
  "Micro, Small & Medium Enterprises",
  "Mines Department",
  "New & Renewable Energy",
  "Personnel & Training",
  "Petroleum & Natural Gas",
  "Planning & Statistics",
  "Ports, Shipping & Waterways",
  "Power Department",
  "Public Works Department",
  "Railways",
  "Revenue Department",
  "Road Transport & Highways",
  "Rural Development",
  "Science & Technology",
  "Skill Development",
  "Social Justice & Empowerment",
  "Steel Department",
  "Textile Department",
  "Tourism Department",
  "Tribal Affairs",
  "Urban Development",
  "Women & Child Development",
  "Youth Affairs & Sports",
] as const;

export const ALL_DESIGNATIONS = [
  "Additional Collector",
  "Additional Commissioner",
  "Additional Director",
  "Additional Secretary",
  "Assistant Collector",
  "Assistant Commissioner",
  "Assistant Director",
  "Block Development Officer (BDO)",
  "Chief Secretary",
  "Chief Medical Officer (CMO)",
  "Collector",
  "Commissioner",
  "Deputy Collector",
  "Deputy Commissioner",
  "Deputy Director",
  "Deputy Secretary",
  "Director",
  "District Development Officer",
  "District Judge",
  "District Magistrate",
  "Inspector General (IG)",
  "Joint Collector",
  "Joint Commissioner",
  "Joint Director",
  "Joint Secretary",
  "Judicial Magistrate",
  "Municipal Commissioner",
  "Principal Secretary",
  "Secretary",
  "Special Officer",
  "Superintendent of Police (SP)",
  "Tahsildar",
  "Under Secretary",
] as const;

export const ROLES = [
  {
    key: "REVIEWER",
    label: "Reviewer",
    desc: "Reviews and approves extracted directives",
    color: "indigo",
  },
  {
    key: "DEPT_USER",
    label: "Dept. User",
    desc: "Views department action plans",
    color: "violet",
  },
  {
    key: "ADMIN",
    label: "Admin",
    desc: "Full system access and user management",
    color: "amber",
  },
] as const;

export type RoleKey = (typeof ROLES)[number]["key"];
